# Generated by Django 3.0.4 on 2020-04-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_permalink'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='gift_has_been_bought',
            field=models.BooleanField(default=False),
        ),
    ]
