# Generated by Django 3.0.4 on 2020-04-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_recipient_gift_has_been_bought'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedgift',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
